language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
script: grunt
after_success: grunt gh-pages:travis
env:
  global:
    secure: bYHbFHeAVEGfv0buxy4i8Kb3ieGR7oM6Z6FUlFsvhFPftIdMZRO6v6HVysIqgL4eVJScBg8PBEuH+tqiEXiTK+sKFAl0MT+V2+GVqyLJHgVLUiTToP9YQ+D9oMyJkzsQF5gyO3RnSWUMordU3uwzfyIn0IoFSG/JLdIVzji1fv4C/0DL21AYKJuVjKMIamjfgB0MR79yWfTikNIXpbhN+BmvCFvUrV1cBNwi8lcvYnToRDnXsVVqhKZjtE2yZNthPOWrSRyvI20C5wLPNxIfe3GvALvKkJyZHWpNfAtfy1NDVEjlaAiUymQtyDmzfempF8vAq3BiaikRVZuez0xTauJIe4k/PqEk+0hp3WgQNMIEfWpvWOvQVzxLfrmyXktKI6EwKGx2eTpZiFtu+4O6DZb6bcSJNihRlUEMrKOnjB7Iwi46AsINwf76WXYq8AMPnnbT4jzjsoKGbrDXR58PZ4FrPakRAYd7mLrwre9B7tWCtB9rJuKyArr9K25U6TOolx0fTav0tiXFJcPpAOivPqSYlbcvIAuCHPuOJszgvZ0Amm3yJGm6PmxAyqk2v780NkGEdBJy4GnqmizyVBHQiWfJtcRxnQXZlh/OH7uJk3ISe5EdKKH2pMNEreg4xZeulmqf/TZCq2X+bWt7cdXm//JaUG8DbVTr9W9Q27TzXfI=
branches:
  only:
  - master
